AWSTemplateFormatVersion: 2010-09-09
Description: root template to call child templates
Resources: 
  PublicSubnets:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://ecsclusterdemo.s3.ap-south-1.amazonaws.com/vpc.yml
  IAMRoles:
    Type: AWS::CloudFormation::Stack 
    DependsOn: 
     - PublicSubnets
    Properties:
      TemplateURL: https://ecsclusterdemo.s3.ap-south-1.amazonaws.com/iam.yml
   EcsCluster:
    Type: AWS::CloudFormation::Stack 
    DependsOn: 
     - IAMRoles
    Properties:
      TemplateURL: https://ecsclusterdemo.s3.ap-south-1.amazonaws.com/app-cluster.yml
   Appversion:
    Type: AWS::CloudFormation::Stack 
    DependsOn: 
     - EcsCluster
    Properties:
      TemplateURL: https://ecsclusterdemo.s3.ap-south-1.amazonaws.com/api.yml
    
     
    
